export const scopeActionTypes = {
    DATA_WARGA_REQUEST: 'DATA_WARGA_REQUEST',
    DATA_WARGA_SUCCESS: 'DATA_WARGA_SUCCESS',
    DATA_WARGA_FAILURE: 'DATA_WARGA_FAILURE',

    AMBIL_AHLI_WARIS_REQUEST: 'AMBIL_AHLI_WARIS_REQUEST',
    AMBIL_AHLI_WARIS_SUCCESS: 'AMBIL_AHLI_WARIS_SUCCESS',
    AMBIL_AHLI_WARIS_FAILURE: 'AMBIL_AHLI_WARIS_FAILURE',

    AMBIL_DATA_IURAN_REQUEST: 'AMBIL_DATA_IURAN_REQUEST',
    AMBIL_DATA_IURAN_SUCCESS: 'AMBIL_DATA_IURAN_SUCCESS',
    AMBIL_DATA_IURAN_FAILURE: 'AMBIL_DATA_IURAN_FAILURE',

    AMBIL_DATA_MINTA_SURAT_REQUEST: 'AMBIL_DATA_MINTA_SURAT_REQUEST',
    AMBIL_DATA_MINTA_SURAT_SUCCESS: 'AMBIL_DATA_MINTA_SURAT_SUCCESS',
    AMBIL_DATA_MINTA_SURAT_FAILURE: 'AMBIL_DATA_MINTA_SURAT_FAILURE',

    TAMPIL_BERITA_REQUEST: 'TAMPIL_BERITA_REQUEST',
    TAMPIL_BERITA_SUCCESS: 'TAMPIL_BERITA_SUCCESS',
    TAMPIL_BERITA_FAILURE: 'TAMPIL_BERITA_FAILURE',


    KIRIM_NOTIF_REQUEST: 'KIRIM_NOTIF_REQUEST',
    KIRIM_NOTIF_SUCCESS: 'KIRIM_NOTIF_SUCCESS',
    KIRIM_NOTIF_FAILURE: 'KIRIM_NOTIF_FAILURE',

    INPUT_IURAN_REQUEST: 'INPUT_IURAN_REQUEST',
    INPUT_IURAN_SUCCESS: 'INPUT_IURAN_SUCCESS',
    INPUT_IURAN_FAILURE: 'INPUT_IURAN_FAILURE',

    // ini harusnya input surat baru
    INPUT_AHLI_WARIS_REQUEST: 'INPUT_AHLI_WARIS_REQUEST',
    INPUT_AHLI_WARIS_SUCCESS: 'INPUT_AHLI_WARIS_SUCCESS',
    INPUT_AHLI_WARIS_FAILURE: 'INPUT_AHLI_WARIS_FAILURE',

    // ini harusnya input surat baru
    INPUT_AHLI_WARIS_REQUEST: 'INPUT_AHLI_WARIS_REQUEST',
    INPUT_AHLI_WARIS_SUCCESS: 'INPUT_AHLI_WARIS_SUCCESS',
    INPUT_AHLI_WARIS_FAILURE: 'INPUT_AHLI_WARIS_FAILURE',

    INPUT_AHLI_WARIS_BARU_REQUEST: 'INPUT_AHLI_WARIS_BARU_REQUEST',
    INPUT_AHLI_WARIS_BARU_SUCCESS: 'INPUT_AHLI_WARIS_BARU_SUCCESS',
    INPUT_AHLI_WARIS_BARU_FAILURE: 'INPUT_AHLI_WARIS_BARU_FAILURE',

}